/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_TRIA_TRIA_PROTOCOL_PB_H_INCLUDED
#define PB_TRIA_TRIA_PROTOCOL_PB_H_INCLUDED
#include <nanopb/pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Rust -> Pico2 (制御コマンド) */
typedef struct _tria_CommandPacket {
    int32_t horizontal_motor;
    int32_t vertical_motor;
    int32_t hand_motor;
    int32_t wheel1;
    int32_t wheel2;
    int32_t wheel3;
} tria_CommandPacket;

/* Pico2 -> Rust (レスポンス) */
typedef struct _tria_SensorPacket {
    int32_t can_id;
    int32_t velocity;
    int32_t angle;
    int32_t torque;
    int32_t horizontal_limit_switch;
    int32_t vertical_limit_switch;
} tria_SensorPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define tria_CommandPacket_init_default          {0, 0, 0, 0, 0, 0}
#define tria_SensorPacket_init_default           {0, 0, 0, 0, 0, 0}
#define tria_CommandPacket_init_zero             {0, 0, 0, 0, 0, 0}
#define tria_SensorPacket_init_zero              {0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define tria_CommandPacket_horizontal_motor_tag  1
#define tria_CommandPacket_vertical_motor_tag    2
#define tria_CommandPacket_hand_motor_tag        3
#define tria_CommandPacket_wheel1_tag            4
#define tria_CommandPacket_wheel2_tag            5
#define tria_CommandPacket_wheel3_tag            6
#define tria_SensorPacket_can_id_tag             1
#define tria_SensorPacket_velocity_tag           2
#define tria_SensorPacket_angle_tag              3
#define tria_SensorPacket_torque_tag             4
#define tria_SensorPacket_horizontal_limit_switch_tag 5
#define tria_SensorPacket_vertical_limit_switch_tag 6

/* Struct field encoding specification for nanopb */
#define tria_CommandPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    horizontal_motor,   1) \
X(a, STATIC,   SINGULAR, INT32,    vertical_motor,    2) \
X(a, STATIC,   SINGULAR, INT32,    hand_motor,        3) \
X(a, STATIC,   SINGULAR, INT32,    wheel1,            4) \
X(a, STATIC,   SINGULAR, INT32,    wheel2,            5) \
X(a, STATIC,   SINGULAR, INT32,    wheel3,            6)
#define tria_CommandPacket_CALLBACK NULL
#define tria_CommandPacket_DEFAULT NULL

#define tria_SensorPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    can_id,            1) \
X(a, STATIC,   SINGULAR, INT32,    velocity,          2) \
X(a, STATIC,   SINGULAR, INT32,    angle,             3) \
X(a, STATIC,   SINGULAR, INT32,    torque,            4) \
X(a, STATIC,   SINGULAR, INT32,    horizontal_limit_switch,   5) \
X(a, STATIC,   SINGULAR, INT32,    vertical_limit_switch,   6)
#define tria_SensorPacket_CALLBACK NULL
#define tria_SensorPacket_DEFAULT NULL

extern const pb_msgdesc_t tria_CommandPacket_msg;
extern const pb_msgdesc_t tria_SensorPacket_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define tria_CommandPacket_fields &tria_CommandPacket_msg
#define tria_SensorPacket_fields &tria_SensorPacket_msg

/* Maximum encoded size of messages (where known) */
#define TRIA_TRIA_PROTOCOL_PB_H_MAX_SIZE         tria_CommandPacket_size
#define tria_CommandPacket_size                  66
#define tria_SensorPacket_size                   66

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
