/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "tria_protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(tria_CommandPacket, tria_CommandPacket, AUTO)


PB_BIND(tria_SensorPacket, tria_SensorPacket, AUTO)



